### ISSUE TITLE
Settings reset on relog/reload and request for slight visual improvements

### ISSUE THREAD

**Issue by Nillx** [drcrazy/CharacterStatsWrath#1]
Heya, thanks for updating this addon. Its nice to see it working again.

Noticed a small issue, every time i relog or reload my UI the settings are reset to default. I usually keep the window on the right closed and  set to display the spell stats. If i reload it goes back to melee stats and the window is showing up. It also seems to reset the options from the settings inside Interface>addons.

Also got a small request, is it possible to reduce the space between the lines slightly? Like 1-2px so the bottom line isnt this close to the weapon icons?

![image](https://user-images.githubusercontent.com/34476875/197557193-e8627036-1793-417a-8fa2-45c463a45dee.png)

Would love if it was showing the % hit and haste instead of the rating, not sure why the original author did it this way.

**Comment by Nillx** [comment]
I actually found a quick fix for the first "issue" i listed. In CharacterStatsWrathUI.lua i changed line 86 to 14 (default 15) and it looks better now. 
![image](https://user-images.githubusercontent.com/34476875/197562511-b548e9fa-774c-480b-aafa-cb5e8254ec8d.png)

**Comment by drcrazy** [comment]
Feel free to submit a PR with you change.

**Comment by drcrazy** [comment]
Thank you for detailed report. 
Both points are fixed. Release will be in 1-2 days.

**Comment by Nillx** [comment]
Thanks and im not that familiar how PRs work. It was just a number change.
