### ISSUE TITLE
crit cap

### ISSUE THREAD

**Issue by seldrinia** [drcrazy/CharacterStatsWrath#2]
Hello firstly thank you for this app :). I noticed you put the crit cap for a lvl 73 npc... wich is not very usefull for us at lvl 80 ^^. Maybe a miss.

Have a nice day !

**Comment by drcrazy** [comment]
Hello, 

thank you for using CharacterStatsWrath.  It might be just overlooks in strings, but I will double check the math.

**Comment by drcrazy** [comment]
Ranged crit cap updated in cfa673e3075287d4a0288a3160599d0792ea1f1d
